version: '3'
services:
    app1:
        image: ianwijaya/hackazon
        hostname: app1
        ports:
        - "8081:80"
    app2:
        image: ianwijaya/hackazon
        hostname: app2
        ports:
        - "8082:80"
    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8000:8000"
